repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: check-xml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: forbid-submodules
-   repo: https://github.com/collective/zpretty
    rev: 3.1.0
    hooks:
    -   id: zpretty
