overrides:
    - files:
          - "*.xml"
          - "*.yml"

          - "*.index"
      options:
          printWidth: 4
    - files:
          - "*.md"
      options:
          printWidth: 180
printWidth: 160
tabWidth: 4
useTabs: false
singleQuote: false
requirePragma: false
bracketSpacing: true
trailingComma: "none"
objectWrap: "preserve"
embeddedLanguageFormatting: "auto"
endOfLine: "lf"
