repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.7.1
    hooks:
    -   id: check-yaml
    -   id: check-xml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-illegal-windows-names
    -   id: forbid-submodules
