name: Format Style
on:
  push:
    branches: [ '**' ]
    tags-ignore: [ '**' ]
    paths:
      - '**.index'
      - '**.xml'
  pull_request:
    branches: [ '**' ]
    tags-ignore: [ '**' ]
    paths:
      - '**.index'
      - '**.xml'
  workflow_dispatch:
concurrency:
  group: Format Style
  cancel-in-progress: true
permissions:
  contents: write
  pull-requests: write
jobs:
  format-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@main
      - name: Formatting with style
        uses: findologic/intellij-format-action@main
      - name: Checking for changes
        id: cfc
        run: |
          if git diff HEAD --quiet; then
            echo diff=false >> $GITHUB_ENV
          else
            echo diff=true >> $GITHUB_ENV
          fi
      - name: Create Pull Request
        id: cpr
        if: github.repository == 'GustavoSchip/elements-gus' && steps.cfc.outputs.diff == true
        uses: peter-evans/create-pull-request@main
        with:
          commit-message: Formatted with style
          title: Formatter[bot]
          body: Formatted with style
          branch: master-format
      - uses: peter-evans/enable-pull-request-automerge@main
        if: github.repository == 'GustavoSchip/elements-gus' && steps.cfc.outputs.diff == true
        with:
          pull-request-number: '${{ steps.cpr.outputs.pull-request-number }}'
          merge-method: squash