name: Publish Wiki
on:
  push:
    branches: [ 'master' ]
    tags-ignore: [ '**' ]
    paths:
      - 'wiki/**'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.run_id }}
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  check-formatting:
    strategy:
      fail-fast: true
    uses: GustavoSchip/elements-gus/.github/workflows/format-style.yml@master
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
  publish-wiki:
    strategy:
        fail-fast: true
    needs: check-formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@main
      - name: Publishing processed Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@master
        with:
          path: 'wiki/'
          strategy: init
