name: Publish Wiki
on:
  push:
    branches: [ 'master' ]
    tags-ignore: [ '**' ]
    paths:
      - 'wiki/**'
  workflow_dispatch:
concurrency:
  group: Publish Wiki
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  process-placeholders:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@main
      - name: Placeholder processing the wiki
        uses: richardrigutins/replace-in-files@main
        with:
          files: 'wiki/*.md'
          search-text: '{{ GITHUB_REPO }}'
          replacement-text: '${{ github.server_url }}/${{ github.repository }}'
  formatting-wiki:
    needs: process-placeholders
    uses: GustavoSchip/elements-gus/.github/workflows/format-style.yml@main
    secrets: inherit
  publish-wiki:
    needs: formatting-wiki
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@main
      - name: Publishing processed Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@master
        with:
          path: 'wiki/'
          strategy: init
